// ============================================================
// src/motor.cpp
//
// Simulation engine of the mechanistic functional response model of
// Okuyama (2012, 2026), compiled with Rcpp.
//
// One foraging trial (duration T, H hosts):
//   * search time      ~ Gamma(shape = k, rate = k * a * H^z)
//   * host attacked    = floor(runif(0, H))   (hosts chosen at random)
//   * handling time    ~ Lognormal with mean h and standard deviation s
//                        (natural scale, as in Okuyama 2026); s = 0 gives
//                        a fixed handling time h
//   * the trial ends when the elapsed time exceeds T
//   * the response is the number of DISTINCT hosts attacked.
//
// Saturation cut-off (exact): once all H hosts have been attacked the
// response cannot change any more, so the trial is stopped there. This
// does not alter the simulated distribution but removes pathological
// run times when h and k approach zero (or a * H^z is huge).
//
// Random numbers: the exported wrapper generated by Rcpp already opens
// an RNGScope, so none is opened here (a nested RNGScope re-reads
// .Random.seed and repeats random numbers). The user controls the
// stream through set.seed(); no seed is ever set inside the package.
// ============================================================

#include <Rcpp.h>
#include <cmath>
#include <vector>

using namespace Rcpp;

// [[Rcpp::export]]
IntegerVector motor_okuyama_cpp(int H, double a, double h, double z,
                                double k, double s, double T,
                                int nsim, bool corte_saturacion = true) {
    if (H < 1) stop("H must be >= 1");
    if (nsim < 1) stop("nsim must be >= 1");
    if (!(a > 0) || !(k > 0) || !(h >= 0) || !(s >= 0) || !(T > 0) ||
        !R_finite(a) || !R_finite(k) || !R_finite(h) || !R_finite(s) || !R_finite(z))
        stop("invalid parameters (need finite a > 0, k > 0, h >= 0, s >= 0, T > 0)");

    IntegerVector out(nsim);
    std::vector<unsigned char> tocado(H);

    // Gamma scale = 1 / (k * a * H^z); same order of operations as the
    // reference R implementation (simulate_trial()).
    const double rate = k * a * R_pow((double) H, z);
    const double escala_gamma = 1.0 / rate;

    // Lognormal parameters (once per call)
    const bool manip_fija = (s == 0);
    double ln_mu = 0.0, ln_sd = 0.0;
    if (!manip_fija) {
        if (!(h > 0)) stop("h must be > 0 when s > 0");
        ln_sd = std::sqrt(std::log(1 + (s / h) * (s / h)));
        ln_mu = std::log(h) - 0.5 * ln_sd * ln_sd;
    }

    for (int sim = 0; sim < nsim; ++sim) {
        std::fill(tocado.begin(), tocado.end(), 0);
        int distintos = 0;
        double t = 0.0;

        while (t < T) {
            t += R::rgamma(k, escala_gamma);
            if (t > T) break;

            int pid = (int) std::floor(R::runif(0, H));
            if (!tocado[pid]) { tocado[pid] = 1; ++distintos; }
            if (corte_saturacion && distintos == H) break;

            t += manip_fija ? h : std::exp(R::rnorm(ln_mu, ln_sd));
        }

        out[sim] = distintos;
        if (sim % 1000 == 0) Rcpp::checkUserInterrupt();
    }
    return out;
}

// Total number of while-loop iterations over nsim trials (diagnostic
// used by the tests to show that the saturation cut-off removes the
// computational trap h ~ 0, k ~ 0). Returns Inf if max_vueltas is hit.
// [[Rcpp::export]]
double contar_vueltas_cpp(int H, double a, double h, double z,
                          double k, double s, double T, int nsim,
                          bool corte_saturacion, double max_vueltas = 1e9) {
    if (H < 1) stop("H must be >= 1");
    const double rate = k * a * R_pow((double) H, z);
    const double escala_gamma = 1.0 / rate;
    const bool manip_fija = (s == 0);
    const double ln_sd = manip_fija ? 0 : std::sqrt(std::log(1 + (s / h) * (s / h)));
    const double ln_mu = manip_fija ? 0 : std::log(h) - 0.5 * ln_sd * ln_sd;
    std::vector<unsigned char> tocado(H);
    double vueltas = 0;
    for (int sim = 0; sim < nsim; ++sim) {
        std::fill(tocado.begin(), tocado.end(), 0);
        int distintos = 0; double t = 0.0;
        while (t < T) {
            t += R::rgamma(k, escala_gamma);
            if (t > T) break;
            int pid = (int) std::floor(R::runif(0, H));
            if (!tocado[pid]) { tocado[pid] = 1; ++distintos; }
            vueltas += 1;
            if (vueltas >= max_vueltas) return R_PosInf;
            if (corte_saturacion && distintos == H) break;
            t += manip_fija ? h : std::exp(R::rnorm(ln_mu, ln_sd));
        }
        if (sim % 1000 == 0) Rcpp::checkUserInterrupt();
    }
    return vueltas;
}
