// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// motor_okuyama_cpp
IntegerVector motor_okuyama_cpp(int H, double a, double h, double z, double k, double s, double T, int nsim, bool corte_saturacion);
RcppExport SEXP _funresMech_motor_okuyama_cpp(SEXP HSEXP, SEXP aSEXP, SEXP hSEXP, SEXP zSEXP, SEXP kSEXP, SEXP sSEXP, SEXP TSEXP, SEXP nsimSEXP, SEXP corte_saturacionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< bool >::type corte_saturacion(corte_saturacionSEXP);
    rcpp_result_gen = Rcpp::wrap(motor_okuyama_cpp(H, a, h, z, k, s, T, nsim, corte_saturacion));
    return rcpp_result_gen;
END_RCPP
}
// contar_vueltas_cpp
double contar_vueltas_cpp(int H, double a, double h, double z, double k, double s, double T, int nsim, bool corte_saturacion, double max_vueltas);
RcppExport SEXP _funresMech_contar_vueltas_cpp(SEXP HSEXP, SEXP aSEXP, SEXP hSEXP, SEXP zSEXP, SEXP kSEXP, SEXP sSEXP, SEXP TSEXP, SEXP nsimSEXP, SEXP corte_saturacionSEXP, SEXP max_vueltasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< bool >::type corte_saturacion(corte_saturacionSEXP);
    Rcpp::traits::input_parameter< double >::type max_vueltas(max_vueltasSEXP);
    rcpp_result_gen = Rcpp::wrap(contar_vueltas_cpp(H, a, h, z, k, s, T, nsim, corte_saturacion, max_vueltas));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_funresMech_motor_okuyama_cpp", (DL_FUNC) &_funresMech_motor_okuyama_cpp, 9},
    {"_funresMech_contar_vueltas_cpp", (DL_FUNC) &_funresMech_contar_vueltas_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_funresMech(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
