# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

motor_okuyama_cpp <- function(H, a, h, z, k, s, T, nsim, corte_saturacion = TRUE) {
    .Call(`_funresMech_motor_okuyama_cpp`, H, a, h, z, k, s, T, nsim, corte_saturacion)
}

contar_vueltas_cpp <- function(H, a, h, z, k, s, T, nsim, corte_saturacion, max_vueltas = 1e9) {
    .Call(`_funresMech_contar_vueltas_cpp`, H, a, h, z, k, s, T, nsim, corte_saturacion, max_vueltas)
}

